import { Metadata } from "next";
import HomeClient from "./HomeClient";

export const metadata: Metadata = {
  title: "Welcome to zappy",
  description: "Generated by create next app",
};

export default function Home() {
  
  return (
    <HomeClient/>
  );
}
